version: "3"

services:
    postgres:
        image: postgres
        environment:
            - DATABASE_HOST=localhost
            - DATABASE_PORT=postgres
            - DATABASE_USER=postgres
            - DATABASE_PASSWORD=postgres
        ports:
            - "5432:5432"
        volumes:
            - ./pg-data:/var/lib/postgresql/data
            - ./postgres.conf:/etc/postgresql/postgres.conf